data_delivery:
  delivery_mode: symlink
  output_dir: ./full_delivery
  threads: 8
  include_qc_summary: true
  exclude_patterns: []
  
  include_patterns:
    # --- 0. 原始数据 (Raw Data) ---
    - pattern: "00.raw_data/link_dir/*"
      dest: "00_Raw_Data/"  # 加斜杠！表示放入此目录

    # --- 1. 项目汇总 (Summary) ---
    - pattern: "*_summary_table.csv"
      dest: "Summary/"
    - pattern: "*_summary_paths.json"
      dest: "Summary/"
    - pattern: "01.qc/md5_check.tsv"
      dest: "Summary/"

    # --- 2. 质控报告 (QC) ---
    - pattern: "01.qc/fastq_screen_multiqc_r1/"
      dest: "01_QC/FastQ_Screen_R1/"
    - pattern: "01.qc/fastq_screen_multiqc_r2/"
      dest: "01_QC/FastQ_Screen_R2/"
    - pattern: "01.qc/short_read_r1_multiqc/"
      dest: "01_QC/Raw_Data_MultiQC_R1/"
    - pattern: "01.qc/short_read_r2_multiqc/"
      dest: "01_QC/Raw_Data_MultiQC_R2/"
    - pattern: "01.qc/multiqc_short_read_trim/"
      dest: "01_QC/Clean_Data_MultiQC/"
    - pattern: "01.qc/multiqc_merge_qc/"
      dest: "01_QC/Overall_MultiQC/"
    
    # 你的特殊需求：重命名文件
    - pattern: "01.qc/multiqc_merge_qc/multiqc_merge_qc_report_data/multiqc_fastq_screen.txt"
      dest: "Summary/fastq_screen_result.txt" # 这里不要加斜杠，因为是重命名

    # --- 3. 比对结果 (Mapping) ---
    - pattern: "02.mapping/STAR/sort_index/*.sort.bam"
      dest: "02_Mapping/BAM/" # 加斜杠！
    - pattern: "02.mapping/STAR/sort_index/*.sort.bam.bai"
      dest: "02_Mapping/BAM/" # 加斜杠！
    
    - pattern: "02.mapping/bamCoverage/"
      dest: "02_Mapping/BigWig/"
    
    - pattern: "02.mapping/qualimap_report/"
      dest: "02_Mapping/Reports/Qualimap/"
    - pattern: "02.mapping/samtools_flagstat/"
      dest: "02_Mapping/Reports/Flagstat/"
    - pattern: "02.mapping/samtools_stats/"
      dest: "02_Mapping/Reports/Stats/"

    # --- 4. 定量结果 (Expression) ---
    - pattern: "03.count/merge_rsem_counts.tsv"
      dest: "03_Expression/Matrix/"
    - pattern: "03.count/merge_rsem_fpkm.tsv"
      dest: "03_Expression/Matrix/"
    - pattern: "03.count/merge_rsem_tpm.tsv"
      dest: "03_Expression/Matrix/"
    
    - pattern: "03.count/rsem_ultimate/"
      dest: "03_Expression/RSEM_Samples/"
    
    - pattern: "03.count/multiqc_rsem_report.html"
      dest: "03_Expression/Reports/"
    - pattern: "03.count/multiqc_rsem_report_data/"
      dest: "03_Expression/Reports/multiqc_rsem_report_data/"

    # --- 5. 变异检测 (Variant) ---
    - pattern: "04.variant/"
      dest: "04_Variant/"

    # --- 6. 差异表达 (DEG) ---
    - pattern: "06.DEG/"
      dest: "05_DEG/"
    
    # --- 7. 富集分析 (Enrichments) ---
    - pattern: "07.Enrichments/*"
      dest: "06_Enrichments/" # 加斜杠！

    # --- 8. 可变剪切 (AS) ---
    - pattern: "07.AS/"
      dest: "07_AS/"