data_delivery:
  delivery_mode: copy
  exclude_patterns: []
  include_patterns:
  - qc_summary_table.csv
  - qc_summary_paths.json
  - 01.qc/short_read_r1_multiqc/multiqc_*_report.html
  - 01.qc/short_read_r1_multiqc/*report_data
  - 01.qc/short_read_r2_multiqc/multiqc_*_report.html
  - 01.qc/short_read_r2_multiqc/*report_data
  - 01.qc/multiqc_short_read_trim/multiqc_*_report.html
  - 01.qc/multiqc_short_read_trim/*report_data
  - 01.qc/fastq_screen_multiqc_r1/multiqc_*_report.html
  - 01.qc/fastq_screen_multiqc_r1/*report_data
  - 01.qc/fastq_screen_multiqc_r2/multiqc_*_report.html
  - 01.qc/fastq_screen_multiqc_r2/*report_data
  - 01.qc/short_read_trim/*.trimed.json
  - 01.qc/short_read_trim/*.trimed.html
  include_qc_summary: true
  output_dir: ./qc_delivery
  threads: 4